name: breez
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  app_settings: ^4.1.1
  archive: ^3.1.6
  auto_size_text: ^2.1.0 # TODO Version 3 with anytime player update needed
  badges: ^2.0.1
  bip39: ^1.0.6
  collection: ^1.15.0
  confetti: ^0.6.0
  connectivity: ^3.0.6
  crypto: ^3.0.1
  csv: ^5.0.0
  dio: ^4.0.0 # TODO Version 4.0.1 with firebase_core update needed
  drag_and_drop_lists: 0.3.2+1 # TODO Version 0.3.2+2 with dart upgrade needed
  duration: ^3.0.8
  email_validator: ^2.0.1
  extended_image: ^4.2.1 # TODO Version 5 with breaking changes
  file_picker: ^3.0.1 # TODO version 4 with breaking changes or version 3.0.2 with firebase_core update needed
  firebase_core: 0.4.2 # TODO version 1 with breaking changes
                       # or version 0.4.5 with uni_links update needed, (uni_links has not update the platform interface yet)
                       # or version 0.4.3 with dio update needed
  firebase_database: ^3.1.6 # TODO version 5 with breaking changes or version 4 with firebase_core update needed
  firebase_dynamic_links: ^0.5.3 # TODO version 1 with breaking changes or version 0.6 with firebase_core update needed
  firebase_messaging: ^5.1.8 # TODO version 6 with breaking changes
  flushbar: ^1.10.4
  flutter_secure_storage: ^4.2.1
  flutter_svg: ^0.22.0 # TODO version 0.23 with breaking changes
  flutter_web_browser: ^0.15.0
  grpc: ^3.0.2
  hex: ^0.2.0
  image: ^3.0.8
  image_cropper: ^1.4.1
  image_picker: ^0.7.5+4 # TODO version 0.8 with breaking changes
  ini: ^2.1.0
  intl: ^0.17.0
  json_annotation: ^4.0.1 # TODO version 4.2 with json_serializable update needed
  logging: ^1.0.2
  nfc_in_flutter: ^2.0.5
  package_info: ^2.0.2
  path_provider: ^2.0.4 # TODO version 2.0.6 with dart upgrade needed
  printing: ^5.5.0 # TODO version 5.6 with dart upgrade needed
  protobuf: ^2.0.0
  qr_code_scanner: ^0.6.1
  qr_code_tools: ^0.0.7
  qr_flutter: ^4.0.0
  rxdart: ^0.26.0 # TODO version 0.27 with breaking changes
  shared_preferences: ^2.0.7 # TODO version 2.0.8 with dart upgrade needed
  simple_animations: ^1.3.12 # TODO version 2 with breaking changes
  sqflite: ^2.0.0+4
  timeago: ^3.1.0
  tutorial_coach_mark: ^1.1.1
  uni_links: ^0.5.1
  url_launcher: ^6.0.10 # TODO version 6.0.11 with dart upgrade needed
  validators: ^3.0.0
  webdav_client: ^1.1.2
  webview_flutter: ^2.0.13 # TODO version 2.1 with dart upgrade needed

  anytime:
    git:
      url: https://github.com/breez/anytime_podcast_player.git
      ref: b26948955356d717c47eab04fd9a763cf7e9a0b9
  flutter_typeahead:
    git:
      url: https://github.com/breez/flutter_typeahead.git
      ref: 7405b9e3e3a32f605f5951499d2eddc8e45c1f74
  local_auth:
    git:
      url: https://github.com/breez/local_auth.git
      ref: 89649dd86f61f60cf0037d7c3dd418a00fd87692
  share_extend:
    git:
      url: https://github.com/breez/ShareExtend.git

dependency_overrides:
  audio_service: ^0.17.1
  platform: ^3.0.0
  flutter_downloader:
    git:
      url: https://github.com/breez/flutter_downloader.git
  podcast_search:
    git:
      url: https://github.com/breez/podcast_search.git
      ref: 5e867e794261da9b35331261c52ba4d380894a80

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.2 # TODO version 2.1.3 with dart upgrade needed
  json_serializable: ^4.1.3 # TODO version 5 with breaking changes
  mockito: ^5.0.15 # TODO version 5.0.16 with json_serializable upgrade needed
  sqflite_common_ffi: ^2.1.0
  test: any

environment:
  sdk: ^2.10.5
  flutter: ^2.2.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - cert/letsencrypt.cert
    - conf/lnd.conf
    - conf/breez.conf
    - conf/marketplace.conf
    - conf/moonpay.conf
    - src/json/
    - src/images/
    - src/icon/
    - src/icon/animals/
    - src/icon/vendors/
    - src/animations/welcome/
    - src/scripts/
    - src/pos-icons/
    - assets/images/
    - assets/icons/

  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: fonts/IBMPlexSans-Thin.otf
          weight: 100
        - asset: fonts/IBMPlexSans-ThinItalic.otf
          weight: 100
          style: italic
        - asset: fonts/IBMPlexSans-ExtraLight.otf
          weight: 200
        - asset: fonts/IBMPlexSans-ExtraLightItalic.otf
          weight: 200
          style: italic
        - asset: fonts/IBMPlexSans-Light.otf
          weight: 300
        - asset: fonts/IBMPlexSans-LightItalic.otf
          weight: 300
          style: italic
        - asset: fonts/IBMPlexSans-Regular.otf
          weight: 400
        - asset: fonts/IBMPlexSans-Italic.otf
          weight: 400
          style: italic
        - asset: fonts/IBMPlexSans-Medium.otf
          weight: 500
        - asset: fonts/IBMPlexSans-MediumItalic.otf
          weight: 500
          style: italic
        - asset: fonts/IBMPlexSans-SemiBold.otf
          weight: 600
        - asset: fonts/IBMPlexSans-SemiBoldItalic.otf
          weight: 600
          style: italic
        - asset: fonts/IBMPlexSans-Bold.otf
          weight: 700
        - asset: fonts/IBMPlexSans-BoldItalic.otf
          weight: 700
          style: italic
    - family: icomoon
      fonts:
        - asset: fonts/icomoon.ttf
    - family: animals
      fonts:
        - asset: fonts/animals.ttf
    - family: Breez Logo
      fonts:
        - asset: fonts/breezlogo.ttf
    - family: ComfortaaBold
      fonts:
        - asset: fonts/Comfortaa-Bold.ttf
    - family: IBMPlexSansRegular
      fonts:
        - asset: fonts/IBMPlexSans-Regular.ttf
    - family: HacenTunisia
      fonts:
        - asset: fonts/Hacen-Tunisia.ttf
    - family: SAT
      fonts:
        - asset: fonts/sat.otf
