name: breez
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  app_settings: ^4.1.0
  archive: ^3.1.2
  auto_size_text: ^2.1.0
  badges: ^2.0.1
  bip39: ^1.0.6
  collection: ^1.15.0
  confetti: ^0.5.5
  connectivity: ^3.0.3
  crypto: ^3.0.1
  csv: ^5.0.0
  dio: ^4.0.0
  drag_and_drop_lists: ^0.3.2
  duration: ^3.0.6
  file_picker: ^3.0.1
  firebase_core: 0.4.0+3
  firebase_database: ^3.0.0
  firebase_messaging: ^5.0.1+1
  firebase_dynamic_links: ^0.5.0
  flushbar: ^1.10.4
  flutter_secure_storage: ^4.2.0
  flutter_svg: ^0.22.0
  flutter_typeahead:
    git:
      url: https://github.com/breez/flutter_typeahead.git
      ref: 7405b9e3e3a32f605f5951499d2eddc8e45c1f74
  flutter_web_browser: ^0.14.0
  grpc: ^3.0.0
  hex: ^0.2.0
  image: ^3.0.2
  image_cropper: ^1.4.0
  image_picker: ^0.7.4
  ini: ^2.1.0
  intl: ^0.17.0
  json_annotation: ^4.0.1
  logging: ^1.0.1
  nfc_in_flutter: ^2.0.5
  optimized_cached_image: ^2.0.1
  package_info: ^2.0.0
  path_provider: ^2.0.1
  printing: ^5.2.1
  protobuf: ^2.0.0
  qr_code_scanner: ^0.4.0
  qr_code_tools: ^0.0.7
  qr_flutter: ^4.0.0
  rxdart: ^0.26.0
  shared_preferences: ^2.0.5
  simple_animations: ^1.3.12
  sqflite: ^2.0.0+3
  tutorial_coach_mark: ^1.0.0
  uni_links: ^0.5.1
  url_launcher: ^6.0.3
  webview_flutter: 2.0.4

  anytime:
    git:
      url: https://github.com/breez/anytime_podcast_player.git
      ref: 2f007785fdd736f46d288ca96aeee38738951024
  local_auth:
    git:
      url: https://github.com/breez/local_auth.git
      ref: 89649dd86f61f60cf0037d7c3dd418a00fd87692
  share_extend:
    git:
      url: https://github.com/breez/ShareExtend.git

dependency_overrides:
  audio_service: ^0.17.0-nullsafety.0
  platform: ^2.0.0
  flutter_downloader:
    git:
      url: https://github.com/breez/flutter_downloader.git
  podcast_search:
    git:
      url: https://github.com/breez/podcast_search.git
      ref: 59bccd63a1ee8c2ead180fd6575c7e97caeb6254


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.2
  json_serializable: ^4.1.1
  mockito: ^5.0.7
  test: any

environment:
  sdk: '>=2.10.0 <3.0.0'

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - cert/letsencrypt.cert
    - conf/lnd.conf
    - conf/breez.conf
    - conf/marketplace.conf
    - conf/moonpay.conf
    - src/json/
    - src/images/
    - src/icon/
    - src/icon/animals/
    - src/icon/vendors/
    - src/animations/welcome/
    - src/scripts/
    - src/pos-icons/
    - assets/images/
    - assets/icons/

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: fonts/IBMPlexSans-Thin.otf
          weight: 100
        - asset: fonts/IBMPlexSans-ThinItalic.otf
          weight: 100
          style: italic
        - asset: fonts/IBMPlexSans-ExtraLight.otf
          weight: 200
        - asset: fonts/IBMPlexSans-ExtraLightItalic.otf
          weight: 200
          style: italic
        - asset: fonts/IBMPlexSans-Light.otf
          weight: 300
        - asset: fonts/IBMPlexSans-LightItalic.otf
          weight: 300
          style: italic
        - asset: fonts/IBMPlexSans-Regular.otf
          weight: 400
        - asset: fonts/IBMPlexSans-Italic.otf
          weight: 400
          style: italic
        - asset: fonts/IBMPlexSans-Medium.otf
          weight: 500
        - asset: fonts/IBMPlexSans-MediumItalic.otf
          weight: 500
          style: italic
        - asset: fonts/IBMPlexSans-SemiBold.otf
          weight: 600
        - asset: fonts/IBMPlexSans-SemiBoldItalic.otf
          weight: 600
          style: italic
        - asset: fonts/IBMPlexSans-Bold.otf
          weight: 700
        - asset: fonts/IBMPlexSans-BoldItalic.otf
          weight: 700
          style: italic
    - family: icomoon
      fonts:
        - asset: fonts/icomoon.ttf
    - family: animals
      fonts:
        - asset: fonts/animals.ttf
    - family: Breez Logo
      fonts:
        - asset: fonts/breezlogo.ttf
    - family: ComfortaaBold
      fonts:
        - asset: fonts/Comfortaa-Bold.ttf
    - family: IBMPlexSansRegular
      fonts:
        - asset: fonts/IBMPlexSans-Regular.ttf
    - family: HacenTunisia
      fonts:
        - asset: fonts/Hacen-Tunisia.ttf
    - family: SAT
      fonts:
        - asset: fonts/sat.otf
