name: breez
description: A new Flutter project.

dependencies:
  flutter:    
    sdk: flutter
  grpc: ^2.9.0
  protobuf: ^1.1.0
  flutter_slidable: ^0.5.4 
  path_provider: any
  firebase_core: 0.4.0+3
  firebase_database: ^3.0.0
  firebase_messaging: ^5.0.1+1
  firebase_dynamic_links: ^0.5.0
  shared_preferences: ^0.5.1+2
  anytime:
    git:
      url: https://github.com/breez/anytime_podcast_player.git
      ref: f205e5ecb63ff425a21d42941244b68890206301
  share_extend:
    git:
      url: https://github.com/breez/ShareExtend.git
  qr_flutter: ^2.0.0
  hex: "^0.1.1"
  rxdart: "^0.24.1"
  qr_code_tools: "^0.0.6"
  flutter_advanced_networkimage:
    git:
      url: https://github.com/mchome/flutter_advanced_networkimage
  intl: ^0.16.1
  flushbar: ^1.10.4
  qr_code_scanner: ^0.0.13
  image_picker: ^0.5.0+9
  image: any
  package_info: ^0.4.0+13
  uuid: ^2.2.2
  ini: ^2.0.1
  connectivity: ^2.0.0
  logging: ^0.11.3+2  
  json_annotation: any
  http: ^0.12.0+1
  url_launcher: ^5.0.1
  archive: ^2.0.8
  duration: ^2.0.8
  dio: ^3.0.10
  sqflite: ^1.2.1
  badges: ^1.1.1
  simple_animations: ^1.3.9
  file_picker: ^2.0.11
  collection: ^1.14.13

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  
  image_cropper: ^1.3.0
  uni_links: ^0.2.0
  nfc_in_flutter: ^2.0.4
  keyboard_actions: ^2.1.1
  flutter_secure_storage: ^3.2.1+1
  auto_size_text: 2.0.2+1
  app_settings: ^1.0.6+2
  bip39: ^1.0.3
  crypto: ^2.1.2
  flutter_typeahead: ^2.0.0
  csv: ^4.0.3

  local_auth:
    git:
      url: https://github.com/breez/local_auth.git
  drag_and_drop_lists: ^0.2.7
  printing: ^3.7.0
  webview_flutter: ^1.0.7
  flutter_localizations:
    sdk: flutter

dependency_overrides:
  flutter_svg: ^0.18.0
  flutter_downloader:
    git:
      url: https://github.com/breez/flutter_downloader.git
  cupertino_icons: ^1.0.0
  connectivity: ^2.0.0
  podcast_search:
    git:
      url: https://github.com/breez/podcast_search.git
      ref: aa11b3a18682cf407dbadcd9e15dd6b90ab7fad2
  intl: ^0.17.0-nullsafety.2

dev_dependencies:
  mockito: "4.1.3"
  protoc_plugin: ^19.0.1
  build_runner: ^1.0.0
  json_serializable: any
  flutter_test:
    sdk: flutter
  test: any
environment:
  sdk: '>=2.10.0 <3.0.0'

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - cert/letsencrypt.cert
    - conf/lnd.conf
    - conf/breez.conf
    - conf/marketplace.conf
    - conf/moonpay.conf
    - src/json/
    - src/images/
    - src/icon/
    - src/icon/animals/
    - src/icon/vendors/
    - src/animations/welcome/
    - src/scripts/
    - src/pos-icons/

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: fonts/IBMPlexSans-Thin.otf
          weight: 100
        - asset: fonts/IBMPlexSans-ThinItalic.otf
          weight: 100
          style: italic
        - asset: fonts/IBMPlexSans-ExtraLight.otf
          weight: 200
        - asset: fonts/IBMPlexSans-ExtraLightItalic.otf
          weight: 200
          style: italic
        - asset: fonts/IBMPlexSans-Light.otf
          weight: 300
        - asset: fonts/IBMPlexSans-LightItalic.otf
          weight: 300
          style: italic
        - asset: fonts/IBMPlexSans-Regular.otf
          weight: 400
        - asset: fonts/IBMPlexSans-Italic.otf
          weight: 400
          style: italic
        - asset: fonts/IBMPlexSans-Medium.otf
          weight: 500
        - asset: fonts/IBMPlexSans-MediumItalic.otf
          weight: 500
          style: italic
        - asset: fonts/IBMPlexSans-SemiBold.otf
          weight: 600
        - asset: fonts/IBMPlexSans-SemiBoldItalic.otf
          weight: 600
          style: italic
        - asset: fonts/IBMPlexSans-Bold.otf
          weight: 700
        - asset: fonts/IBMPlexSans-BoldItalic.otf
          weight: 700
          style: italic
    - family: icomoon
      fonts:
        - asset: fonts/icomoon.ttf
    - family: animals
      fonts:
        - asset: fonts/animals.ttf
    - family: Breez Logo
      fonts:
        - asset: fonts/breezlogo.ttf
    - family: ComfortaaBold
      fonts:
        - asset: fonts/Comfortaa-Bold.ttf
    - family: IBMPlexSansRegular
      fonts:
        - asset: fonts/IBMPlexSans-Regular.ttf
    - family: HacenTunisia
      fonts:
        - asset: fonts/Hacen-Tunisia.ttf
    - family: SAT
      fonts:
        - asset: fonts/sat.otf
