name: breez
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  grpc: ^0.6.4
  protobuf: any
  path_provider: any
  firebase_database:
    git:
      url: https://github.com/flutter/plugins.git
      path: packages/firebase_database
  firebase_messaging:
    git:
      url: https://github.com/flutter/plugins.git
      path: packages/firebase_messaging
  shared_preferences: "^0.4.1"
  share: "^0.5.2"
  qr_flutter: ^1.1.1
  http: "^0.11.3+16"
  hex: "^0.1.1"
  rxdart: "^0.18.1"  
  flutter_advanced_networkimage: any
  intl: ^0.15.7
  flushbar: ^0.9.0
  barcode_scan: ^0.0.4
  image_picker: 0.4.7
  image: any
  package_info: any  
  uuid: ^1.0.3
  ini:
  connectivity: ^0.3.2
  logging: ^0.11.3+2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  mockito: "^3.0.0"


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - cert/letsencrypt.cert
    - conf/lnd.conf
    - conf/breez.conf
    - src/json/countries.json
    - src/json/states.json
    - src/images/
    - src/icon/
    - src/icon/animals/
    - src/animations/welcome/

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
  fonts:
    - family: IBMPlexSansRegular
      fonts:
        - asset: fonts/IBMPlexSans-Regular.ttf
    - family: IBMPlexSansMedium
      fonts:
        - asset: fonts/IBMPlexSans-Medium.ttf
    - family: IBMPlexSansLight
      fonts:
        - asset: fonts/IBMPlexSans-Light.ttf
    - family: icomoon
      fonts:
        - asset: fonts/icomoon.ttf
    - family: animals
      fonts:
        - asset: fonts/animals.ttf
    - family: Breez Logo
      fonts:
        - asset: fonts/breezlogo.ttf
