name: breez
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  another_flushbar: ^1.10.29
  app_settings: ^4.1.8
  archive: ^3.3.1
  auto_size_text: ^3.0.0
  badges: ^2.0.3
  bip39: ^1.0.6
  collection: ^1.16.0
  confetti: ^0.7.0
  connectivity_plus: ^2.3.6
  crypto: ^3.0.2
  csv: ^5.0.1
  dio: ^4.0.6
  drag_and_drop_lists: # Target this ref until new release
    git:
      url: https://github.com/mauriceraguseinit/DragAndDropLists
      ref: bb224b167574a35f722c9e9fbfa960dbee232ce5
  duration: ^3.0.11
  email_validator: ^2.1.16
  extended_image: ^6.2.1
  file_picker: ^5.0.0
  firebase_core: ^1.20.0
  firebase_database: ^9.0.20
  firebase_dynamic_links: ^4.3.3
  firebase_messaging: ^12.0.1
  flutter_secure_storage: ^5.0.2
  flutter_svg: ^1.1.1+1
  flutter_web_browser: ^0.17.1
  google_api_availability: ^3.0.1
  grpc: ^3.0.2
  hex: ^0.2.0
  image: ^3.2.0
  image_cropper: ^2.0.3
  image_picker: ^0.8.5+3
  ini: ^2.1.0
  intl: ^0.17.0
  json_annotation: ^4.6.0
  local_auth: ^2.1.0
  logging: ^1.0.2
  md5_file_checksum: ^1.0.3
  nfc_manager: ^3.1.1
  package_info_plus: ^1.4.3
  path_provider: ^2.0.11
  printing: ^5.9.2
  protobuf: ^2.1.0
  mobile_scanner: ^2.0.0
  scan: ^1.6.0
  # qr_flutter has already fixed the build issue with the qr package but did not publish an updated
  # version, they will publish as 4.0.1 for now they recommend to use the master but instead of that
  # we are using an specific commit to avoid unexpected behaviour in future builds.
  qr_flutter:
    git:
      url: https://github.com/theyakka/qr.flutter.git
      ref: 1fc6e38c198a76a6fd60b7bd3b4c190cd6c9330b
  rxdart: ^0.27.5
  screenshot: ^1.2.3
  share_plus: ^4.0.10
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  simple_animations: ^4.2.0
  sqflite: ^2.0.3
  timeago: ^3.2.2
  tutorial_coach_mark: ^1.2.3
  uni_links: ^0.5.1
  url_launcher: ^6.1.5
  uuid: ^3.0.6
  validators: ^3.0.0
  webdav_client: ^1.1.8
  webview_flutter: ^3.0.4

  anytime:
    git:
      url: https://github.com/breez/anytime_podcast_player.git
      ref: 13ae1f964fafa0eccd9dc10312a28c611873c2e7
  flutter_typeahead:
    git:
      url: https://github.com/breez/flutter_typeahead.git
      ref: a16aa4deeff1c5e96c6da46da31cb0533f838d8d
  nfc_in_flutter:
    git:
      url: https://github.com/breez/nfc_in_flutter.git
      ref: 97f610be82bfe42d5ce86c348d931d61949fa517
  share_extend:
    git:
      url: https://github.com/breez/ShareExtend.git

dependency_overrides:
  flutter_downloader:
    git:
      url: https://github.com/breez/flutter_downloader.git
      ref: 60a4470a9b552b287d729e230881f9ac77f5b506
  podcast_search:
    git:
      url: https://github.com/breez/podcast_search.git
      ref: 8190101aa49edf0f501cf3688f32a3a87df137c5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  mockito: ^5.2.0
  sqflite_common_ffi: ^2.1.1+1
  test: any

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: 3.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - cert/letsencrypt.cert
    - conf/lnd.conf
    - conf/breez.conf
    - conf/marketplace.conf
    - conf/moonpay.conf
    - src/json/
    - src/images/
    - src/icon/
    - src/icon/animals/
    - src/icon/vendors/
    - src/animations/welcome/
    - src/scripts/
    - src/pos-icons/
    - assets/images/
    - assets/icons/

  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: fonts/IBMPlexSans-Thin.otf
          weight: 100
        - asset: fonts/IBMPlexSans-ThinItalic.otf
          weight: 100
          style: italic
        - asset: fonts/IBMPlexSans-ExtraLight.otf
          weight: 200
        - asset: fonts/IBMPlexSans-ExtraLightItalic.otf
          weight: 200
          style: italic
        - asset: fonts/IBMPlexSans-Light.otf
          weight: 300
        - asset: fonts/IBMPlexSans-LightItalic.otf
          weight: 300
          style: italic
        - asset: fonts/IBMPlexSans-Regular.otf
          weight: 400
        - asset: fonts/IBMPlexSans-Italic.otf
          weight: 400
          style: italic
        - asset: fonts/IBMPlexSans-Medium.otf
          weight: 500
        - asset: fonts/IBMPlexSans-MediumItalic.otf
          weight: 500
          style: italic
        - asset: fonts/IBMPlexSans-SemiBold.otf
          weight: 600
        - asset: fonts/IBMPlexSans-SemiBoldItalic.otf
          weight: 600
          style: italic
        - asset: fonts/IBMPlexSans-Bold.otf
          weight: 700
        - asset: fonts/IBMPlexSans-BoldItalic.otf
          weight: 700
          style: italic
    - family: icomoon
      fonts:
        - asset: fonts/icomoon.ttf
    - family: animals
      fonts:
        - asset: fonts/animals.ttf
    - family: Breez Logo
      fonts:
        - asset: fonts/breezlogo.ttf
    - family: ComfortaaBold
      fonts:
        - asset: fonts/Comfortaa-Bold.ttf
    - family: IBMPlexSansRegular
      fonts:
        - asset: fonts/IBMPlexSans-Regular.ttf
    - family: HacenTunisia
      fonts:
        - asset: fonts/Hacen-Tunisia.ttf
    - family: SAT
      fonts:
        - asset: fonts/sat.otf
