name: breez
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  another_flushbar: ^1.12.30
  app_settings: ^5.1.1
  archive: <=3.4.10 # Requires Flutter 3.10
  audio_service: ^0.18.13
  auto_size_text: ^3.0.0
  badges: <=3.1.1 # Requires Flutter 3.10
  bip39: ^1.0.6
  breez_translations:
    git:
      url: https://github.com/breez/Breez-Translations.git
      ref: a564088448149e9c28b4a2eb82fa0a3536698d24
  clipboard_watcher:
    git:
      url: https://github.com/breez/clipboard_watcher.git
      ref: f2faa4e2c93db77b244cd34e4c8027fd9eca362d
  collection: <=1.17.0 # flutter_test
  confetti: ^0.7.0
  connectivity_plus: <=4.0.2  # anytime
  convert: ^3.1.1
  crypto: ^3.0.3
  csv: ^6.0.0
  device_info_plus: <=9.1.2 # anytime
  dio: ^5.4.3+1
  drag_and_drop_lists: <0.4.0 # drag_and_drop_lists >= 0.4.0 is incompatible with Flutter 3.7.12
  duration: ^3.0.13
  email_validator: ^3.0.0
  extended_image: <=7.0.2 # Requires Flutter 3.10
  ffmpeg_kit_flutter_https_gpl: ^6.0.3
  file_picker: <=5.3.1 # Requires Flutter 3.10
  firebase_core: <=2.24.2 # Requires Flutter 3.10
  firebase_core_platform_interface: ^5.1.0
  firebase_database: <=10.4.0  # Requires Flutter 3.10
  firebase_dynamic_links: <=5.4.8 # Requires Flutter 3.10
  firebase_messaging: <=14.7.10 # Requires Flutter 3.10
  fixnum: ^1.1.0
  flutter_easyloading: ^3.0.5
  flutter_secure_storage: <=8.1.0 # anytime
  flutter_spinkit: ^5.2.1
  flutter_svg: <=2.0.9  #  # Requires Flutter 3.10 - http 1.0.0
  flutter_web_browser: ^0.17.1
  git_info: ^1.1.2
  google_api_availability: ^5.0.0
  grpc: <=3.1.0 # Requires Flutter 3.10
  hex: ^0.2.0
  http: <=0.13.6 # Requires Flutter 3.10
  image: ^4.2.0
  image_cropper: <=4.0.1 # Requires Flutter 3.10
  image_picker: <=1.0.4  # Requires Flutter 3.10
  ini: ^2.1.0
  intl: <=0.17.0 # local_auth
  json_annotation: <=4.8.1 # Requires Flutter 3.10
  local_auth: <=1.1.11 # Can't differentiate between biometric types on local auth 2.0.0+
  logging: ^1.2.0
  meta: <=1.8.0 # flutter_test
  md5_file_checksum:
    git:
      url: https://github.com/breez/md5_file_checksum.git
  mobile_scanner: <=3.5.7 # Requires Flutter 3.10
  nfc_manager: ^3.5.0
  nostr_tools: <=1.0.7 # Requires Flutter 3.10(depends on http ^1.1.0)
  package_info_plus: <=4.2.0 # Requires Flutter 3.10
  path: <=1.8.2 # flutter_test(^1.8.2) anytime(^1.8.3)
  path_provider: <=2.1.1 # Requires Flutter 3.10
  path_provider_platform_interface: <=2.1.1 # Requires Flutter 3.10
  pdf: ^3.11.0
  plugin_platform_interface: <=2.1.6 # Requires Flutter 3.10
  printing: <=5.10.4 # Requires Flutter 3.10
  protobuf: <=2.1.0 # Requires Flutter 3.10
  provider: ^6.1.2
  # qr_flutter has already fixed the build issue with the qr package but did not publish an updated
  # version, they will publish as 4.0.1 for now they recommend to use the master but instead of that
  # we are using an specific commit to avoid unexpected behaviour in future builds.
  qr_flutter:
    git:
      url: https://github.com/theyakka/qr.flutter.git
      ref: 1fc6e38c198a76a6fd60b7bd3b4c190cd6c9330b
  rxdart: ^0.27.7 # anytime
  screenshot: <=1.3.0 # Requires Flutter 3.10
  share_plus: <=7.2.2 # anytime
  shared_preferences: <=2.2.2 # Requires Flutter 3.10
  shimmer: ^3.0.0
  simple_animations: ^5.0.2
  sqflite: <=2.2.8+4 # Requires Flutter 3.10
  store_checker: ^1.4.0
  timeago: ^3.6.1
  tutorial_coach_mark: ^1.2.11
  uni_links: ^0.5.1
  url_launcher: <=6.1.11 # Requires Flutter 3.10
  uuid: <=4.2.2  # Requires Flutter 3.10
  validators: ^3.0.0
  webdav_client: ^1.2.2
  webview_flutter: <=4.4.2 # Requires Flutter 3.10
  webview_flutter_android: <=3.12.1 # Requires Flutter 3.10

  anytime:
    git:
      url: https://github.com/breez/anytime_podcast_player.git
      ref: db9f878aa640954aa272e92bd7a5c364683179a9
  flutter_downloader:
    git:
      url: https://github.com/breez/flutter_downloader.git
      ref: c9cbc56c6d1c8bb434301757be84ac1e65d046c6
  flutter_typeahead:
    git:
      url: https://github.com/breez/flutter_typeahead.git
      ref: a16aa4deeff1c5e96c6da46da31cb0533f838d8d
  podcast_search:
    git:
      url: https://github.com/breez/podcast_search.git
      ref: a2dfc441a6ba3c506ef15b1dd881a03d15254ccf
  nfc_in_flutter:
    git:
      url: https://github.com/breez/nfc_in_flutter.git
      ref: 97f610be82bfe42d5ce86c348d931d61949fa517

dependency_overrides:
  intl: <=0.18.1 # anytime
  meta: <=1.9.1 # anytime
  path: <=1.8.3
  flutter_downloader:
    git:
      url: https://github.com/breez/flutter_downloader.git
      ref: c9cbc56c6d1c8bb434301757be84ac1e65d046c6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: <=2.3.3 # Requires Flutter 3.10
  json_serializable: <=6.6.2 # Requires Flutter 3.10
  mockito: <=5.4.0 # mockito >=5.4.1 <5.4.3 depends on matcher ^0.12.15 and mockito >=5.4.3 requires SDK version >=3.1.0 <4.0.0
  sqflite_common_ffi: <=2.2.5 # Requires Flutter 3.10
  test: any
  flutter_lints: <=2.0.3 # Requires Flutter 3.10

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=3.7.12"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - cert/letsencrypt.cert
    - conf/lnd.conf
    - conf/breez.conf
    - conf/moonpay.conf
    - src/json/
    - src/images/
    - src/icon/
    - src/icon/animals/
    - src/icon/vendors/
    - src/animations/welcome/
    - src/scripts/
    - src/pos-icons/
    - assets/images/
    - assets/icons/
    - .git/
    - .git/refs/heads/

  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: fonts/IBMPlexSans-Thin.otf
          weight: 100
        - asset: fonts/IBMPlexSans-ThinItalic.otf
          weight: 100
          style: italic
        - asset: fonts/IBMPlexSans-ExtraLight.otf
          weight: 200
        - asset: fonts/IBMPlexSans-ExtraLightItalic.otf
          weight: 200
          style: italic
        - asset: fonts/IBMPlexSans-Light.otf
          weight: 300
        - asset: fonts/IBMPlexSans-LightItalic.otf
          weight: 300
          style: italic
        - asset: fonts/IBMPlexSans-Regular.otf
          weight: 400
        - asset: fonts/IBMPlexSans-Italic.otf
          weight: 400
          style: italic
        - asset: fonts/IBMPlexSans-Medium.otf
          weight: 500
        - asset: fonts/IBMPlexSans-MediumItalic.otf
          weight: 500
          style: italic
        - asset: fonts/IBMPlexSans-SemiBold.otf
          weight: 600
        - asset: fonts/IBMPlexSans-SemiBoldItalic.otf
          weight: 600
          style: italic
        - asset: fonts/IBMPlexSans-Bold.otf
          weight: 700
        - asset: fonts/IBMPlexSans-BoldItalic.otf
          weight: 700
          style: italic
    - family: icomoon
      fonts:
        - asset: fonts/icomoon.ttf
    - family: animals
      fonts:
        - asset: fonts/animals.ttf
    - family: Breez Logo
      fonts:
        - asset: fonts/breezlogo.ttf
    - family: ComfortaaBold
      fonts:
        - asset: fonts/Comfortaa-Bold.ttf
    - family: IBMPlexSansRegularEnableBackupDialog
      fonts:
        - asset: fonts/IBMPlexSans-Regular.ttf
    - family: HacenTunisia
      fonts:
        - asset: fonts/Hacen-Tunisia.ttf
    - family: SAT
      fonts:
        - asset: fonts/sat.otf
