name: breez
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  app_settings: ^4.1.6
  archive: ^3.1.9
  auto_size_text: ^3.0.0
  badges: ^2.0.2
  bip39: ^1.0.6
  collection: ^1.15.0 # Outdated
  confetti: ^0.6.0
  connectivity_plus: ^2.2.0
  crypto: ^3.0.1
  csv: ^5.0.1
  dio: ^4.0.6
  drag_and_drop_lists: ^0.3.2+2
  duration: ^3.0.11
  email_validator: ^2.0.1
  extended_image: ^6.0.2+1
  file_picker: ^4.5.1
  firebase_core: ^1.15.0
  firebase_database: ^9.0.12
  firebase_dynamic_links: ^4.2.0
  firebase_messaging: ^11.2.14
  flushbar: ^1.10.4 # discontinued
  flutter_secure_storage: ^5.0.2
  flutter_svg: ^1.0.3
  flutter_web_browser: ^0.16.0
  google_api_availability: ^3.0.1
  grpc: ^3.0.2
  hex: ^0.2.0
  image: ^3.1.1
  image_cropper: ^1.5.1
  image_picker: ^0.8.5
  ini: ^2.1.0
  intl: ^0.17.0
  json_annotation: ^4.4.0
  logging: ^1.0.2
  package_info_plus: ^1.4.2
  path_provider: ^2.0.8
  printing: ^5.7.5
  protobuf: ^2.0.1
  qr_code_scanner: ^0.6.1
  qr_code_tools: ^0.0.7
  # qr_flutter has already fixed the build issue with the qr package but did not publish an updated
  # version, they will publish as 4.0.1 for now they recommend to use the master but instead of that
  # we are using an specific commit to avoid unexpected behaviour in future builds.
  qr_flutter:
    git:
      url: https://github.com/theyakka/qr.flutter.git
      ref: 1fc6e38c198a76a6fd60b7bd3b4c190cd6c9330b
  rxdart: ^0.27.3
  shared_preferences: ^2.0.12
  simple_animations: ^4.0.1
  sqflite: ^2.0.2
  timeago: ^3.2.1
  tutorial_coach_mark: ^1.2.1
  uni_links: ^0.5.1
  url_launcher: ^6.0.18
  uuid: ^3.0.5
  validators: ^3.0.0
  webdav_client: ^1.1.2
  webview_flutter: ^3.0.2

  anytime:
    git:
      url: https://github.com/breez/anytime_podcast_player.git
      ref: a682f1bceb73ce676067385ba10e42b383f94391
  flutter_typeahead:
    git:
      url: https://github.com/breez/flutter_typeahead.git
      ref: 7405b9e3e3a32f605f5951499d2eddc8e45c1f74
  local_auth:
    git:
      url: https://github.com/breez/local_auth.git
      ref: 89649dd86f61f60cf0037d7c3dd418a00fd87692
  nfc_in_flutter:
    git:
      url: https://github.com/breez/nfc_in_flutter.git
      ref: 97f610be82bfe42d5ce86c348d931d61949fa517
  share_extend:
    git:
      url: https://github.com/breez/ShareExtend.git
  md5_file_checksum: ^1.0.3

dependency_overrides:
  flutter_downloader:
    git:
      url: https://github.com/breez/flutter_downloader.git
      ref: c3e528b
  podcast_search:
    git:
      url: https://github.com/breez/podcast_search.git
      ref: e5edaea

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.8
  json_serializable: ^6.1.4
  mockito: ^5.0.17
  sqflite_common_ffi: ^2.1.0+2
  test: any

environment:
  sdk: ^2.10.5

flutter:
  uses-material-design: true
  generate: true

  assets:
    - cert/letsencrypt.cert
    - conf/lnd.conf
    - conf/breez.conf
    - conf/marketplace.conf
    - conf/moonpay.conf
    - src/json/
    - src/images/
    - src/icon/
    - src/icon/animals/
    - src/icon/vendors/
    - src/animations/welcome/
    - src/scripts/
    - src/pos-icons/
    - assets/images/
    - assets/icons/

  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: fonts/IBMPlexSans-Thin.otf
          weight: 100
        - asset: fonts/IBMPlexSans-ThinItalic.otf
          weight: 100
          style: italic
        - asset: fonts/IBMPlexSans-ExtraLight.otf
          weight: 200
        - asset: fonts/IBMPlexSans-ExtraLightItalic.otf
          weight: 200
          style: italic
        - asset: fonts/IBMPlexSans-Light.otf
          weight: 300
        - asset: fonts/IBMPlexSans-LightItalic.otf
          weight: 300
          style: italic
        - asset: fonts/IBMPlexSans-Regular.otf
          weight: 400
        - asset: fonts/IBMPlexSans-Italic.otf
          weight: 400
          style: italic
        - asset: fonts/IBMPlexSans-Medium.otf
          weight: 500
        - asset: fonts/IBMPlexSans-MediumItalic.otf
          weight: 500
          style: italic
        - asset: fonts/IBMPlexSans-SemiBold.otf
          weight: 600
        - asset: fonts/IBMPlexSans-SemiBoldItalic.otf
          weight: 600
          style: italic
        - asset: fonts/IBMPlexSans-Bold.otf
          weight: 700
        - asset: fonts/IBMPlexSans-BoldItalic.otf
          weight: 700
          style: italic
    - family: icomoon
      fonts:
        - asset: fonts/icomoon.ttf
    - family: animals
      fonts:
        - asset: fonts/animals.ttf
    - family: Breez Logo
      fonts:
        - asset: fonts/breezlogo.ttf
    - family: ComfortaaBold
      fonts:
        - asset: fonts/Comfortaa-Bold.ttf
    - family: IBMPlexSansRegular
      fonts:
        - asset: fonts/IBMPlexSans-Regular.ttf
    - family: HacenTunisia
      fonts:
        - asset: fonts/Hacen-Tunisia.ttf
    - family: SAT
      fonts:
        - asset: fonts/sat.otf
