name: breez
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  another_flushbar: ^1.12.29
  app_settings: ^4.2.0
  archive: ^3.3.6
  auto_size_text: ^3.0.0
  badges: ^2.0.3 #
  bip39: ^1.0.6
  breez_translations:
    git:
      url: https://github.com/breez/Breez-Translations.git
      ref: 9c8cc35d9e289a9696ab15ad91734ff12739b171
  confetti: ^0.7.0
  connectivity_plus: ^2.3.9 #
  crypto: ^3.0.2
  csv: ^5.0.1
  dio: ^4.0.6
  drag_and_drop_lists: ^0.3.3
  duration: ^3.0.12
  email_validator: ^2.1.17
  extended_image: ^6.4.0
  ffmpeg_kit_flutter_https_gpl: ^5.1.0
  file_picker: ^5.2.5
  firebase_core: ^2.4.1
  # Version 4.5.2 breaks, it is necessary to update firebase as a whole
  firebase_core_platform_interface: ^4.5.2
  firebase_database: ^10.0.9
  firebase_dynamic_links: ^5.0.11
  firebase_messaging: ^14.2.1
  flutter_secure_storage: ^7.0.1
  flutter_svg: ^1.1.6 #
  flutter_web_browser: ^0.17.1
  google_api_availability: ^3.0.1
  grpc: ^3.1.0
  hex: ^0.2.0
  image: ^3.3.0 #
  image_cropper: ^3.0.1
  image_picker: ^0.8.6+1
  ini: ^2.1.0
  intl: ^0.18.0
  json_annotation: ^4.8.0
  local_auth: <2.0.0 #
  logging: ^1.1.1
  md5_file_checksum: ^1.0.4
  nfc_manager: ^3.2.0
  package_info_plus: ^3.0.2
  path_provider: ^2.0.12
  printing: ^5.9.3 #
  protobuf: ^2.1.0
  mobile_scanner: ^2.1.0
  # qr_flutter has already fixed the build issue with the qr package but did not publish an updated
  # version, they will publish as 4.0.1 for now they recommend to use the master but instead of that
  # we are using an specific commit to avoid unexpected behaviour in future builds.
  qr_flutter:
    git:
      url: https://github.com/theyakka/qr.flutter.git
      ref: 1fc6e38c198a76a6fd60b7bd3b4c190cd6c9330b
  rxdart: ^0.27.7
  screenshot: ^1.3.0
  share_plus: ^6.3.0
  shared_preferences: ^2.0.17
  shimmer: ^2.0.0
  simple_animations: ^5.0.0+3
  sqflite: ^2.2.4+1
  timeago: ^3.3.0
  tutorial_coach_mark: ^1.2.4
  uni_links: ^0.5.1
  url_launcher: ^6.1.9
  uuid: ^3.0.7
  validators: ^3.0.0
  webdav_client: ^1.1.8
  webview_flutter: ^4.0.2

  anytime:
    git:
      url: https://github.com/breez/anytime_podcast_player.git
      ref: 4169cd904b93bda16837fe3e28d42fe26731905d
  flutter_typeahead:
    git:
      url: https://github.com/breez/flutter_typeahead.git
      ref: a16aa4deeff1c5e96c6da46da31cb0533f838d8d
  nfc_in_flutter:
    git:
      url: https://github.com/breez/nfc_in_flutter.git
      ref: 97f610be82bfe42d5ce86c348d931d61949fa517

dependency_overrides:
  collection: ^1.17.1
  intl: ^0.18.0
  meta: ^1.9.0
  path: ^1.8.3
  flutter_downloader:
    git:
      url: https://github.com/breez/flutter_downloader.git
      ref: 7a90641a687e27cc3cb451389f1281faceeef56f
  podcast_search:
    git:
      url: https://github.com/breez/podcast_search.git
      ref: 8190101aa49edf0f501cf3688f32a3a87df137c5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  mockito: ^5.3.2
  sqflite_common_ffi: ^2.2.1+1
  test: any

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=3.7.1"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - cert/letsencrypt.cert
    - conf/lnd.conf
    - conf/breez.conf
    - conf/moonpay.conf
    - src/json/
    - src/images/
    - src/icon/
    - src/icon/animals/
    - src/icon/vendors/
    - src/animations/welcome/
    - src/scripts/
    - src/pos-icons/
    - assets/images/
    - assets/icons/

  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: fonts/IBMPlexSans-Thin.otf
          weight: 100
        - asset: fonts/IBMPlexSans-ThinItalic.otf
          weight: 100
          style: italic
        - asset: fonts/IBMPlexSans-ExtraLight.otf
          weight: 200
        - asset: fonts/IBMPlexSans-ExtraLightItalic.otf
          weight: 200
          style: italic
        - asset: fonts/IBMPlexSans-Light.otf
          weight: 300
        - asset: fonts/IBMPlexSans-LightItalic.otf
          weight: 300
          style: italic
        - asset: fonts/IBMPlexSans-Regular.otf
          weight: 400
        - asset: fonts/IBMPlexSans-Italic.otf
          weight: 400
          style: italic
        - asset: fonts/IBMPlexSans-Medium.otf
          weight: 500
        - asset: fonts/IBMPlexSans-MediumItalic.otf
          weight: 500
          style: italic
        - asset: fonts/IBMPlexSans-SemiBold.otf
          weight: 600
        - asset: fonts/IBMPlexSans-SemiBoldItalic.otf
          weight: 600
          style: italic
        - asset: fonts/IBMPlexSans-Bold.otf
          weight: 700
        - asset: fonts/IBMPlexSans-BoldItalic.otf
          weight: 700
          style: italic
    - family: icomoon
      fonts:
        - asset: fonts/icomoon.ttf
    - family: animals
      fonts:
        - asset: fonts/animals.ttf
    - family: Breez Logo
      fonts:
        - asset: fonts/breezlogo.ttf
    - family: ComfortaaBold
      fonts:
        - asset: fonts/Comfortaa-Bold.ttf
    - family: IBMPlexSansRegular
      fonts:
        - asset: fonts/IBMPlexSans-Regular.ttf
    - family: HacenTunisia
      fonts:
        - asset: fonts/Hacen-Tunisia.ttf
    - family: SAT
      fonts:
        - asset: fonts/sat.otf
